<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 3/16/16
 * Time: 5:42 PM
 */

namespace Admin\Controller;


use Common\Controller\AuthController;
use Common\Tools;

class PerformanceController extends AuthController
{
    protected $Depart; //部门模型
    public $Message; //留言模型

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->Depart = D('Depart');
        $this->Message = D('Message');
    }

    public function performance_index(){}

    /**
     * 留言询价处理
     */
    public function messageAndInquiryProcessing()
    {
        $this->display();
    }
}