<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 3/16/16
 * Time: 5:42 PM
 */

namespace Admin\Controller;


use Admin\FixedData;
use Common\Controller\AuthController;
use Common\Tools;

class PerformanceController extends AuthController
{
    use FixedData;

    protected $DepartMember; //部门模型
    public $Message; //留言模型

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->DepartMember = D('DepartMember');
        $this->Message = D('Message');
    }

    public function performance_index(){}

    /**
     * 留言询价处理
     */
    public function messageAndInquiryProcessing()
    {
        $departmembers = $this->DepartMember->where(['bumen'=>1])->field(['id'=>'member_id','username','bumen'=>'depart_id'])->order()->limit()->select();
        foreach($departmembers as $k => $v){
            $departmembers[$k]['depart_name'] = $this->depart_data[$v['depart_id']]['depart_name'];
            $x = D('Member')->where(['username'=>$v['username']])->field(['truename'])->find();
            $departmembers[$k]['member_name'] = $x['truename'];
            // 留言统计
            $departmembers[$k]['message_status'] = $this->getMessage($v['username'],true);
            // 询价统计
            $departmembers[$k]['inquiry_status'] = $this->getInquiry($v['username'],true);
        }
        $this->assign(['departmembers'=>$departmembers]);
        $this->display();
    }

    /**
     * ajax询价处理
     */
    public function getAjaxInquiryProcessing()
    {
        $column_index = [
            "message_id",
            "message_title",
            "member_username",
            "member_truename",
            "product_id",
            "product_title",
            "product_standard",
            "price",
            "addtime",
        ];
        $column_search = [
            "message.itemid",
            "message.title",
            "member.username",
            "member.truename",
            "product.itemid",
            "product.title",
            "product.standard",
            "product.price",
            "message.addtime",
        ];
        $draw = $_GET['draw'];//这个值作者会直接返回给前台
        $start = $_GET['start'];
        $limit = $_GET['length'];
        $order = $_GET['order'];
        $order = "{$column_index[$order[0]['column']]} {$order[0]['dir']}";
        foreach ($_GET['columns'] as $k => $v) {
            if ($v['search']['value'] != '') {
                $y[] = "{$column_search[$v['data']]} LIKE '%{$v[search][value]}%'";
            }
        }
        $search = '';
        if (count($y) > 0) {
            $search = " AND " . Tools::arr2str($y, " AND ");
        }

        $sql = "SELECT COUNT(message.itemid) AS total
            FROM __MALL_message AS message
            INNER JOIN __MALL_sell_5 AS product ON message.cpid = product.itemid
            INNER JOIN __MALL_member AS member ON message.msgbelong = member.username
            WHERE message.is_xunjia = 1";
        $z = $this->MallDb->list_query($sql);
        $total = $z[0]['total'];
        $sql = "SELECT  message.itemid AS message_id, message.title AS message_title, message.addtime AS addtime,
                member.username AS member_username, member.truename AS member_truename,
                product.itemid AS product_id, product.title AS product_title, product.standard AS product_standard, product.price AS price
            FROM __MALL_message AS message
            INNER JOIN __MALL_sell_5 AS product ON message.cpid = product.itemid
            INNER JOIN __MALL_member AS member ON message.msgbelong = member.username
            WHERE message.is_xunjia = 1 {$search}
            ORDER BY {$order}
            LIMIT {$start}, {$limit}";
        $data = $this->MallDb->list_query($sql);

        foreach ($data as $k => $v) {
            foreach ($column_index as $key => $value) {
                $x[$k][] = $v[$value];
            }
        }
        //获取Datatables发送的参数 必要
        $show = [
            "draw" => $draw,
            "recordsTotal" => $total,
            "recordsFiltered" => $total,
            "data" => $x,
        ];
        $x = json_encode($show);
        echo $x;
    }

    /**
     * 留言统计
     */
    private function getMessage($depart_name,$getStatusCount=false,$field=false)
    {
        if($getStatusCount){
            $yes = $this->Message->where(['msgbelong'=>$depart_name,'answer'=>['NEQ','']])->field("COUNT(itemid) AS count")->select();
            $no = $this->Message->where(['msgbelong'=>$depart_name,'answer'=>['EQ','']])->field("COUNT(itemid) AS count")->select();
            $message_info['count_yes'] = $yes[0]['count'];
            $message_info['count_no'] = $no[0]['count'];
            $message_info['total'] = $yes[0]['count'] + $no[0]['count'];
            $message_info['disposal_rate'] = ($message_info['count_yes']*100/$message_info['total']) . "%" ;
        }

        return $message_info;
    }

    /**
     * 询价统计
     */
    private function getInquiry($depart_name,$getStatusCount=false,$field=false)
    {
        if($getStatusCount){
            $sql = "SELECT message.itemid, message.addtime, message.fixtime, product.price FROM __MALL_message AS message
                LEFT JOIN __MALL_sell_5 AS product ON message.cpid = product.itemid
                WHERE message.msgbelong = '{$depart_name}'";
            $x = $this->MallDb->list_query($sql);
            $inquiry_info['count_no'] = 0;
            $inquiry_info['count_yes'] = 0;
            $inquiry_info['count_timeout'] = 0;
            $inquiry_info['total'] = 0;
            foreach($x as $k => $v){
                if($v['price'] == 0){
                    $inquiry_info['count_no']++;
                }else{
                    $inquiry_info['count_yes'] ++;
                    $_time = $v['fixtime'] - $v['addtime'];
                    if($_time>24*3600){
                        $inquiry_info['count_timeout']++;
                    }
                }
            }
            $inquiry_info['total'] = $inquiry_info['count_no'] + $inquiry_info['count_yes'];
            $inquiry_info['disposal_rate'] = ($inquiry_info['count_yes']*100/$inquiry_info['total']) . "%";
            $inquiry_info['disposal_time_rate'] = (($inquiry_info['count_yes'] - $inquiry_info['count_timeout'])*100/$inquiry_info['total']) . "%";
        }
        return $inquiry_info;
    }
}