<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 1/14/16
 * Time: 10:15 AM
 */

namespace Common\Model;


abstract class BusinessModel extends CommonModel
{
    protected $connection;
    protected $tablePrefix;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->connection = C('BUSINESS_DB');
        $this->tablePrefix = C('BUSINESS_DB_TABLE_PREFIX');
    }
}